version: '3.6'
services:
  user:
    build:
      context: .
      dockerfile: user.Dockerfile
    image: auth:latest
    ports:
      - '8080:8080'
  postgres:
    image: "postgres:11-alpine"
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
